spring.application.name=cayduoclieu
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysqldl-quyhslc11-3e33.k.aivencloud.com:19160/defaultdb?ssl-mode=REQUIRED&allowPublicKeyRetrieval=true&useSSL=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_TJ63v8n1b_1S--RCq0O
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.id.new_generator_mappings=false

spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.main.lazy-initialization=false

springdoc.swagger-ui.path=/swagger-ui-custom.html
springdoc.swagger-ui.operationsSorter=method
springdoc.api-docs.path=/api-docs

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.template-resolver-order=1

gemini.api.key=
security.jwt.secret=${SECURITY_JWT_SECRET:change-me-in-prod}
